/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package delombok.spaces;

import lombok.extern.java.Log;

@Log
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
